var CURRENT_OPTIONS = {};

var DUMMY_PASSWORD_OPTION = 'dummyPasswordOption';
var LOG_OPTION = 'logOption';

CURRENT_OPTIONS[DUMMY_PASSWORD_OPTION] = '0Pa$$4uM^t3';
CURRENT_OPTIONS[LOG_OPTION] = false;
